### ISSUE TITLE
在windows上如何编译使用h264 decode

### ISSUE THREAD

**Issue by shadowlemon233** [dji-sdk/RoboMaster-SDK#14]
如何在windows上编译使用h264 decode？无法在windows上找到libopus-dev, libavcodec-dev, libswscale-dev这几个依赖，是否有替代的依赖？

**Comment by grwhale-zhang** [comment]
最新版本已经提供了windows的版本，详见：https://github.com/dji-sdk/RoboMaster-SDK/tree/master/sample_code/RoboMasterEP/stream/decoder/windows

是否能满足您这边的需求

**Comment by shadowlemon233** [comment]
非常感谢

**Comment by grwhale-zhang** [comment]
如果这边没什么问题，就关闭这个ISSUE了。

多谢您的支持！
