### ISSUE TITLE
RM-S1是否支持

### ISSUE THREAD

**Issue by Just5D** [dji-sdk/RoboMaster-SDK#3]
直连模式下，运行例程未能链接，提示：
PS C:\Users\ou> & C:/Users/ou/AppData/Local/Programs/Python/Python36/python.exe d:/Dev_Proj/RobotMaster/rm_sdk.py
Connecting...
Traceback (most recent call last):
  File "d:/Dev_Proj/RobotMaster/rm_sdk.py", line 51, in <module>
    main()
  File "d:/Dev_Proj/RobotMaster/rm_sdk.py", line 19, in main
    s.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by grwhale-zhang** [comment]
S1暂不支持。
详见https://www.dji.com/cn/robomaster-ep/faq

**Comment by Just5D** [comment]
好的 谢谢回复；可是现在RM-EP会面向零售客户吗，目前看起来都是面向中小学

**Comment by grwhale-zhang** [comment]
非SDK相关问题麻烦咨询 dev@dji.com 哈

**Comment by elonzh** [comment]
> S1暂不支持。
> 详见[dji.com/cn/robomaster-ep/faq](https://www.dji.com/cn/robomaster-ep/faq)

有计划支持吗?

**Comment by zzb1967736495** [comment]
太贵了，S1不支持SDK就是个玩具，ep价格听说最低9500，不适合小学生和个人开发者玩

**Comment by grwhale-zhang** [comment]
> > S1暂不支持。
> > 详见[dji.com/cn/robomaster-ep/faq](https://www.dji.com/cn/robomaster-ep/faq)
> 
> 有计划支持吗?

目前暂无计划哈

**Comment by grwhale-zhang** [comment]
> 太贵了，S1不支持SDK就是个玩具，ep价格听说最低9500，不适合小学生和个人开发者玩

感谢关注和建议反馈~

EP购买咨询详见 https://www.dji.com/cn/robomaster-ep#contact，请根据个人实际需求选购哈

**Comment by brunoga** [comment]
I know for a fact that the S1, even at the current firmware does include at least a partial SDK implementation (in fact, I can run SDK programs on my S1 although one needs root access to enable the SDK on it). Not making it available on the S1 without the need for a hack would be an even bigger mistake than not making the EP compatible with the S1. So I would strongly suggest you consider enabling the S1 SDK support.

**Comment by grwhale-zhang** [comment]
> I know for a fact that the S1, even at the current firmware does include at least a partial SDK implementation (in fact, I can run SDK programs on my S1 although one needs root access to enable the SDK on it). Not making it available on the S1 without the need for a hack would be an even bigger mistake than not making the EP compatible with the S1. So I would strongly suggest you consider enabling the S1 SDK support.

Thank you for your advice, we will consider it carefully. For this issue, we suggest that you report it on the https://security.dji.com, and we will contact you to deal with it.

For more information on how to upgrade S1 to EP, please pay attention to the DJI official website.
