### ISSUE TITLE
请增加对 ARM 平台的支持

### ISSUE THREAD

**Issue by GwenXD** [dji-sdk/RoboMaster-SDK#30]
树莓派、Jetson Nano 无法通过 pip 直接安装 SDK

**Comment by xitinglin-dji** [comment]
> 树莓派、Jetson Nano 无法通过 pip 直接安装 SDK

已经支持pip直接安装sdk，树莓派的安装教程已提供，可以查看文档安装

**Comment by cyrilknops** [comment]
Are you using python 3.7? pip won't find the package in python 3.8

**Comment by xitinglin-dji** [comment]
> Are you using python 3.7? pip won't find the package in python 3.8

whl link: https://pypi.org/project/robomaster/0.1.1.62/#files  , only supports python 64bit
