### ISSUE TITLE
请增加对 Apple M1 芯片的支持

### ISSUE THREAD

**Issue by GwenXD** [dji-sdk/RoboMaster-SDK#33]
![](https://hwj-tuchuang.oss-cn-hangzhou.aliyuncs.com/5858A511-8985-47B6-9CF3-A42C531F2700.jpeg)

M1 芯片的 MacBook Pro 无法安装 RoboMaster SDK

Python 版本：Python3.9 和 Python3.8 均无法安装

**Comment by GwenXD** [comment]
通过 Anaconda 安装 Python 3.7 环境再 pip install robomaster 即可解决

**Comment by GwenXD** [comment]
通过 Anaconda 安装 Python 3.7 环境再 pip install robomaster 即可解决

**Comment by ACChe** [comment]
用了python3.7也装不上。

**Comment by GwenXD** [comment]
> 用了python3.7也装不上。

请附上环境，以及具体的出错内容
