### ISSUE TITLE
Installing Robomaster SDK on Python3.9 (Windows)

### ISSUE THREAD

**Issue by MrCampbellDuchess** [dji-sdk/RoboMaster-SDK#45]
"Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement robomaster (from versions: none)
ERROR: No matching distribution found for robomaster"

Ignore the first line.

I'm able to get this installed at home but not on my work PC, the only difference between the two is the python version.  I read somewhere on another thread that it needs to be 3.8, any work on updating the package to 3.9?

**Comment by elinxer** [comment]
Can you share your solutions？
