### ISSUE TITLE
Installing Robomaster SDK on Python3.9.5[mac book air ]

### ISSUE THREAD

**Issue by elinxer** [dji-sdk/RoboMaster-SDK#50]
"Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement robomaster (from versions: none)
ERROR: No matching distribution found for robomaster"

**Comment by JohnieBraaf** [comment]
You need to build it yourself (libmedia-codec) because the repo does not have a python 3.9 version

**Comment by elinxer** [comment]
i have switched to py3.8, thx
