### ISSUE TITLE
RM SDK can't get the Infrared Distance Sensor data

### ISSUE THREAD

**Issue by alexchenfeng** [dji-sdk/RoboMaster-SDK#90]
Hi:

I meet a sdk problem, can't get Infrared Distance Sensor data, when only using plaintext sdk I can get Sensor data, so how can I using the RM Python SDK to get the data?

I review the SDK code, found that I need to construct a protoco object for IR Distance Sensor, then using self._client.send_sync_msg(msg) function to send the msg to the robot, but what is the _cmdset  and _cmdid of IR Distance Sensor.

Thank you.

**Comment by brunoga** [comment]
You are not supposed to use protos directly or manually send them to the robot. You are supposed to use the higher level API. Check sensor.py in the SDK. You will see there is a DistanceSensor class.
